#  如果使用prometheus operator中的servicemonitor来做服务发现，下面yaml可供参考
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: falcon2p8s-exporter
  name: falcon2p8s-exporter
  namespace: monitoring
spec:
  endpoints:
  - interval: 61s
    path: /metrics
    port: tcp-9090-9090
    relabelings:
    - action: replace
      regex: .*
      replacement: falcon2p8s
      sourceLabels:
      - __address__
      targetLabel: instance
    - action: labeldrop
      regex: endpoint|namespace|service
    scheme: http
    scrapeTimeout: 20s
  namespaceSelector:
    matchNames:
    - monitoring
  selector:
    matchLabels:
      app: falcon2p8s-exporter

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: falcon2p8s-exporter
  name: falcon2p8s-exporter
  namespace: monitoring
spec:
  ports:
  - name: tcp-9090-9090
    port: 9090
    protocol: TCP
    targetPort: 9090
  type: ClusterIP

--- 

apiVersion: v1
kind: Endpoints
metadata:
  labels:
    app: falcon2p8s-exporter
  name: falcon2p8s-exporter
  namespace: monitoring
subsets:
- addresses:
  - ip: 192.168.1.1
  - ip: 192.168.1.2
  ports:
  - name: tcp-9090-9090
    port: 9090
    protocol: TCP